version: '3.8'

services:
    web:
        image: instant-messaging-laravel-chat:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        depends_on:
            - db
        entrypoint: ["./docker-entrypoint.sh"]
        volumes:
            - .:/var/www/html

    db:
        image: mysql:8.0
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./dbdata:/var/lib/mysql

volumes:
    dbdata:
